version: '3.3'

services:

  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: always

  frontend:
    image: deyterriy/foodgram_front
    volumes:
      - static:/app/frontend_static
    command: cp -r /app/build/. /app/frontend_static

  backend:
    image: deyterriy/foodgram_back
    env_file: .env
    volumes:
      - static:/app/web
      - media:/app/media
    depends_on:
      - frontend
      - db
    restart: always

  nginx:
    image: deyterriy/foodgram_gate
    env_file: .env
    volumes:
      - static:/web
      - media:/web/media
    ports:
      - 8080:80
    restart: always

volumes:
  static:
  media:
  pg_data:
